spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      properties:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:~/Desktop/dev/h2;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: null
    driverClassName: org.h2.Driver